

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_Attendance_Project.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Student_AttendanceEntities : DbContext
{
    public Student_AttendanceEntities()
        : base("name=Student_AttendanceEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Tb_Building> Tb_Building { get; set; }

    public virtual DbSet<Tb_Faculty> Tb_Faculty { get; set; }

    public virtual DbSet<Tb_Holiday> Tb_Holiday { get; set; }

    public virtual DbSet<Tb_Room> Tb_Room { get; set; }

    public virtual DbSet<Tb_SchoolYear> Tb_SchoolYear { get; set; }

    public virtual DbSet<Tb_Status> Tb_Status { get; set; }

    public virtual DbSet<Tb_Student> Tb_Student { get; set; }

    public virtual DbSet<Tb_StudentCheck> Tb_StudentCheck { get; set; }

    public virtual DbSet<Tb_Subject> Tb_Subject { get; set; }

    public virtual DbSet<Tb_Login> Tb_Login { get; set; }

    public virtual DbSet<Tb_Schedule> Tb_Schedule { get; set; }

    public virtual DbSet<Tb_NoteTeach> Tb_NoteTeach { get; set; }

    public virtual DbSet<Tb_Department> Tb_Department { get; set; }

    public virtual DbSet<Tb_StudyGroup> Tb_StudyGroup { get; set; }

    public virtual DbSet<Tb_User> Tb_User { get; set; }

}

}

