//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Attendance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Department()
        {
            this.Tb_StudyGroup = new HashSet<Tb_StudyGroup>();
            this.Tb_User = new HashSet<Tb_User>();
        }
    
        public int DeptCode { get; set; }
        public string DeptName { get; set; }
        public string ShortName { get; set; }
        public int FacultyCode { get; set; }
    
        public virtual Tb_Faculty Tb_Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_StudyGroup> Tb_StudyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_User> Tb_User { get; set; }
    }
}
