
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_Attendance_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_GroupTask
{

    public int GroupID { get; set; }

    public int StdID { get; set; }

    public Nullable<double> Score { get; set; }



    public virtual Tb_Group Tb_Group { get; set; }

    public virtual Tb_Student Tb_Student { get; set; }

}

}
