//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Attendance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Login
    {
        public int LoginID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string sessionID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual Tb_User Tb_User { get; set; }
    }
}
