//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Attendance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Room()
        {
            this.Tb_Schedule = new HashSet<Tb_Schedule>();
        }
    
        public string RoomNo { get; set; }
        public string BuildingCode { get; set; }
    
        public virtual Tb_Building Tb_Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Schedule> Tb_Schedule { get; set; }
    }
}
