//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Attendance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_StudyGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_StudyGroup()
        {
            this.Tb_NoteTeach = new HashSet<Tb_NoteTeach>();
            this.Tb_Schedule = new HashSet<Tb_Schedule>();
            this.Tb_Student = new HashSet<Tb_Student>();
            this.Tb_StudentCheck = new HashSet<Tb_StudentCheck>();
        }
    
        public int StudyGroupID { get; set; }
        public string StudyGroupCode { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public int SchYearID { get; set; }
        public string SubjectCode { get; set; }
        public string Course { get; set; }
        public int UserID { get; set; }
    
        public virtual Tb_Department Tb_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_NoteTeach> Tb_NoteTeach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Schedule> Tb_Schedule { get; set; }
        public virtual Tb_SchoolYear Tb_SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Student> Tb_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_StudentCheck> Tb_StudentCheck { get; set; }
        public virtual Tb_Subject Tb_Subject { get; set; }
        public virtual Tb_User Tb_User { get; set; }
    }
}
