
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_Attendance_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Subject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Subject()
    {

        this.Tb_StudyGroup = new HashSet<Tb_StudyGroup>();

    }


    public string SubjectCode { get; set; }

    public string Course { get; set; }

    public string SubjectName { get; set; }

    public string SubjectNameEN { get; set; }

    public double Condition { get; set; }

    public int SubjectTheory { get; set; }

    public int TimeTheory { get; set; }

    public int SubjectPractice { get; set; }

    public int TimePractice { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_StudyGroup> Tb_StudyGroup { get; set; }

}

}
