//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Attendance_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SchoolYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_SchoolYear()
        {
            this.Tb_Schedule = new HashSet<Tb_Schedule>();
            this.Tb_StudyGroup = new HashSet<Tb_StudyGroup>();
        }
    
        public int SchYearID { get; set; }
        public string Term { get; set; }
        public string Year { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime StartMidterm { get; set; }
        public System.DateTime EndMidterm { get; set; }
        public System.DateTime StartFinal { get; set; }
        public System.DateTime EndFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Schedule> Tb_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_StudyGroup> Tb_StudyGroup { get; set; }
    }
}
