
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Students_Attendance_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Task
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Task()
    {

        this.Tb_Group = new HashSet<Tb_Group>();

        this.Tb_SingleTask = new HashSet<Tb_SingleTask>();

    }


    public int TaskID { get; set; }

    public Nullable<int> Type { get; set; }

    public string TaskName { get; set; }

    public Nullable<int> FullScore { get; set; }

    public string Note { get; set; }

    public Nullable<int> StudyGroupID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Group> Tb_Group { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_SingleTask> Tb_SingleTask { get; set; }

    public virtual Tb_StudyGroup Tb_StudyGroup { get; set; }

}

}
